name: Docker CI Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.Docker_Username }}  # Modifié pour correspondre
          password: ${{ secrets.docker_password }}  # Modifié pour correspondre

      - name: Build Docker Image
        run : docker build -t ${{ secrets.Docker_Username }}/flask-app:v2 .  # Modifié aussi ici
        
      - name: Push Docker Image
        run : docker push ${{ secrets.Docker_Username }}/flask-app:v2  # Modifié aussi ici